# Generated by Django 5.0.3 on 2026-04-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_user_experience_years_user_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_welcome',
            field=models.BooleanField(default=False),
        ),
    ]
